In [28]:
import pandas as pd

In [29]:
url="https://raw.githubusercontent.com/datasets/world-religion-projections/main/rounded_percentage.csv"

In [67]:
df=pd.read_csv('by_rounded_percentage_share_csv.csv')

In [68]:
df

,Year,Region,Country,Buddhists,Christians,Folk Religions,Hindus,Jews,Muslims,Other Religions,Unaffiliated
0,2010,World,All Countries,7.1,31.4,5.9,15.0,1.0,23.2,1.0,16.4
1,2010,North America,All Countries,1.1,77.4,1.0,1.0,1.8,1.0,1.0,17.1
2,2010,Latin America-Caribbean,All Countries,1.0,90.0,1.7,1.0,1.0,1.0,1.0,7.7
3,2010,Europe,All Countries,1.0,74.5,1.0,1.0,1.0,5.9,1.0,18.8
4,2010,Middle East-North Africa,All Countries,1.0,3.7,1.0,1.0,1.6,93.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1200,2050,Sub-Saharan Africa,Zimbabwe,1.0,86.1,4.9,1.0,1.0,1.1,1.0,7.6
1201,2050,Sub-Saharan Africa,South Sudan,1.0,60.5,32.9,1.0,1.0,6.2,1.0,1.0
1202,2050,Latin America-Caribbean,Curacao,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3
1203,2050,Latin America-Caribbean,Sint Maarten,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3
1204,2050,Latin America-Caribbean,Caribbean Netherlands,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3

In [86]:
my_series = df.iloc[:,1:11].max(numeric_only=True, axis =1 )
my_series.name = "maxval"

# Include maxval in df
df['maxval']=my_series

In [87]:
df

,Year,Region,Country,Buddhists,Christians,Folk Religions,Hindus,Jews,Muslims,Other Religions,Unaffiliated,maxval
0,2010,World,All Countries,7.1,31.4,5.9,15.0,1.0,23.2,1.0,16.4,31.4
1,2010,North America,All Countries,1.1,77.4,1.0,1.0,1.8,1.0,1.0,17.1,77.4
2,2010,Latin America-Caribbean,All Countries,1.0,90.0,1.7,1.0,1.0,1.0,1.0,7.7,90.0
3,2010,Europe,All Countries,1.0,74.5,1.0,1.0,1.0,5.9,1.0,18.8,74.5
4,2010,Middle East-North Africa,All Countries,1.0,3.7,1.0,1.0,1.6,93.0,1.0,1.0,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1200,2050,Sub-Saharan Africa,Zimbabwe,1.0,86.1,4.9,1.0,1.0,1.1,1.0,7.6,86.1
1201,2050,Sub-Saharan Africa,South Sudan,1.0,60.5,32.9,1.0,1.0,6.2,1.0,1.0,60.5
1202,2050,Latin America-Caribbean,Curacao,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9
1203,2050,Latin America-Caribbean,Sint Maarten,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9
1204,2050,Latin America-Caribbean,Caribbean Netherlands,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9

In [90]:
df['Religion'] = df.loc[:,'Buddhists':'Unaffiliated'].eq(df['maxval'], axis=0).apply(lambda x: ','.join(df.columns[3:11][x==x.max()]),axis=1)
df

,Year,Region,Country,Buddhists,Christians,Folk Religions,Hindus,Jews,Muslims,Other Religions,Unaffiliated,maxval,Religion
0,2010,World,All Countries,7.1,31.4,5.9,15.0,1.0,23.2,1.0,16.4,31.4,Christians
1,2010,North America,All Countries,1.1,77.4,1.0,1.0,1.8,1.0,1.0,17.1,77.4,Christians
2,2010,Latin America-Caribbean,All Countries,1.0,90.0,1.7,1.0,1.0,1.0,1.0,7.7,90.0,Christians
3,2010,Europe,All Countries,1.0,74.5,1.0,1.0,1.0,5.9,1.0,18.8,74.5,Christians
4,2010,Middle East-North Africa,All Countries,1.0,3.7,1.0,1.0,1.6,93.0,1.0,1.0,93.0,Muslims
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,2050,Sub-Saharan Africa,Zimbabwe,1.0,86.1,4.9,1.0,1.0,1.1,1.0,7.6,86.1,Christians
1201,2050,Sub-Saharan Africa,South Sudan,1.0,60.5,32.9,1.0,1.0,6.2,1.0,1.0,60.5,Christians
1202,2050,Latin America-Caribbean,Curacao,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9,Christians
1203,2050,Latin America-Caribbean,Sint Maarten,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9,Christians
1204,2050,Latin America-Caribbean,Caribbean Netherlands,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9,Christians

In [91]:
df1=df[df['Year']==2010]

In [92]:
df1

,Year,Region,Country,Buddhists,Christians,Folk Religions,Hindus,Jews,Muslims,Other Religions,Unaffiliated,maxval,Religion
0,2010,World,All Countries,7.1,31.4,5.9,15.0,1.0,23.2,1.0,16.4,31.4,Christians
1,2010,North America,All Countries,1.1,77.4,1.0,1.0,1.8,1.0,1.0,17.1,77.4,Christians
2,2010,Latin America-Caribbean,All Countries,1.0,90.0,1.7,1.0,1.0,1.0,1.0,7.7,90.0,Christians
3,2010,Europe,All Countries,1.0,74.5,1.0,1.0,1.0,5.9,1.0,18.8,74.5,Christians
4,2010,Middle East-North Africa,All Countries,1.0,3.7,1.0,1.0,1.6,93.0,1.0,1.0,93.0,Muslims
...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,2010,Sub-Saharan Africa,Zimbabwe,1.0,87.0,3.8,1.0,1.0,1.0,1.0,7.9,87.0,Christians
237,2010,Sub-Saharan Africa,South Sudan,1.0,60.5,32.9,1.0,1.0,6.2,1.0,1.0,60.5,Christians
238,2010,Latin America-Caribbean,Curacao,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9,Christians
239,2010,Latin America-Caribbean,Sint Maarten,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9,Christians
240,2010,Latin America-Caribbean,Caribbean Netherlands,1.0,93.9,1.2,1.0,1.0,1.0,1.0,3.3,93.9,Christians

In [93]:
df1.to_csv('religionall.csv')

In [94]:
df2=df1[['Country','Religion']]

In [95]:
df2

                   Country    Religion
0            All Countries  Christians
1            All Countries  Christians
2            All Countries  Christians
3            All Countries  Christians
4            All Countries     Muslims
..                     ...         ...
236               Zimbabwe  Christians
237            South Sudan  Christians
238                Curacao  Christians
239           Sint Maarten  Christians
240  Caribbean Netherlands  Christians

[241 rows x 2 columns]

In [96]:
df2.to_csv('countryreligion.csv')